name = "GMT"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GMT"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
linter.style.header = false
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "GMT"
