name: Lean Action CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Read access to repository contents
  pages: write # Write access to GitHub Pages
  id-token: write # Write access to ID tokens

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: leanprover/lean-action@v1
        with:
          use-github-cache: false
      - uses: leanprover-community/docgen-action@v1
